"""Add one-to-many tasks in employee

Revision ID: 15d3692e7d7c
Revises: 6b991e7b0098
Create Date: 2025-02-09 21:54:57.389375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d3692e7d7c'
down_revision: Union[str, None] = '6b991e7b0098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_assignee_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'employees', ['employee_id'], ['id'])
    op.drop_column('tasks', 'assignee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assignee_fkey', 'tasks', 'employees', ['assignee'], ['id'])
    op.drop_column('tasks', 'employee_id')
    # ### end Alembic commands ###
