"""Add many-to-many rel for parent and child tasks

Revision ID: fc94812f1014
Revises: 15d3692e7d7c
Create Date: 2025-03-10 12:56:38.397859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc94812f1014'
down_revision: Union[str, None] = '15d3692e7d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_to_task',
    sa.Column('parent_task_id', sa.Integer(), nullable=False),
    sa.Column('child_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_task_id', 'child_task_id')
    )
    op.drop_column('tasks', 'parent_task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('task_to_task')
    # ### end Alembic commands ###
